# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


class TestUntitled():
    def setup_method(self):
        self.driver = webdriver.Chrome("C:\\chromedriver.exe")
        self.driver.maximize_window()
        self.vars = {}

    def teardown_method(self):
        self.driver.close()
        self.driver.quit()

    def test_untitled(self):
        self.driver.get("https://www.google.ca/")
        self.driver.find_element(By.NAME, "q").send_keys("Anand Soraganvi")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        self.driver.get_screenshot_as_file("Google.png")


T = TestUntitled()
T.setup_method()
T.test_untitled()
T.teardown_method()
