# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


class TestDefaultSuite():
    def setup_method(self):
        self.driver = webdriver.Chrome("C:/Users/anaso/PycharmProjects/Selenium/Selenium Scripts/Drivers/chromedriver.exe")
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_a1(self):
        self.driver.get("https://fs2.formsite.com/meherpavan/form2/index.html?1537702596407")
        self.driver.set_window_size(1552, 840)
        self.driver.find_element(By.ID, "RESULT_TextField-1").click()
        self.driver.find_element(By.ID, "RESULT_TextField-1").send_keys("Anand")
        self.driver.find_element(By.ID, "RESULT_TextField-2").click()
        self.driver.find_element(By.ID, "RESULT_TextField-2").send_keys("Soraganvi")
        self.driver.find_element(By.ID, "RESULT_TextField-3").click()
        self.driver.find_element(By.ID, "RESULT_TextField-3").send_keys("3333333333")
        self.driver.find_element(By.ID, "RESULT_TextField-4").click()
        self.driver.find_element(By.ID, "RESULT_TextField-4").send_keys("dasdasdas")
        self.driver.find_element(By.ID, "RESULT_TextField-5").click()
        self.driver.find_element(By.ID, "RESULT_TextField-5").send_keys("asdasdasdas")
        self.driver.find_element(By.ID, "RESULT_TextField-6").click()
        self.driver.find_element(By.ID, "RESULT_TextField-6").send_keys("abcd@abcd.com")
        self.driver.find_element(By.CSS_SELECTOR, "#q26 tr:nth-child(1) label").click()
        self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(2) > label").click()
        self.driver.find_element(By.ID, "RESULT_RadioButton-9").click()
        dropdown = self.driver.find_element(By.ID, "RESULT_RadioButton-9")
        dropdown.find_element(By.XPATH, "//option[. = 'Morning']").click()
        self.driver.find_element(By.ID, "RESULT_RadioButton-9").click()
        self.driver.find_element(By.CSS_SELECTOR, ".icon_calendar").click()
        self.driver.find_element(By.LINK_TEXT, "19").click()
        element = self.driver.find_element(By.LINK_TEXT, "Software Testing Tutorials")
        element.location_once_scrolled_into_view
        self.driver.find_element(By.ID, "RESULT_TextArea-12").click()
        self.driver.find_element(By.ID, "RESULT_TextArea-12").send_keys("adads")
        self.driver.find_element(By.ID, "FSsubmit").click()


if __name__=='__main__':

    pytest.main()